//! 音频元数据读写,用 lofty crate。
//!
//! 替代 Python 端的 mutagen。读 opus/m4a/mp3 的:
//!   - title / artist / album / date 文本标签
//!   - synopsis / description(YT Music 的「Provided to YouTube by」签名在这里,用于来源识别)
//!   - duration(秒)
//!   - 是否有封面
//!
//! 同时提供"来源识别":classify_source 用 synopsis 的签名判断正版编录 vs 普通视频。
//! 对应 Python `list_non_catalog.py`。

use lofty::file::{AudioFile, TaggedFileExt};
use lofty::tag::ItemKey;
use serde::Serialize;
use std::path::Path;

#[derive(Serialize, Clone)]
pub struct AudioMeta {
    pub title: Option<String>,
    pub artist: Option<String>,
    pub album: Option<String>,
    pub date: Option<String>,
    /// opus 的 synopsis 字段(YT Music 的「Provided to YouTube by」签名在这里)
    pub synopsis: Option<String>,
    /// description / comment
    pub description: Option<String>,
    /// purl(YouTube 链接,可提取 videoId)
    pub purl: Option<String>,
    pub duration: Option<f64>,
    pub has_cover: bool,
}

/// 来源分类。对应 Python `list_non_catalog.classify_source`。
/// - catalog: synopsis 含「Provided to YouTube by」(正版编录)
/// - catalog_no_album: 是编录但 album 空
/// - non_catalog: 普通视频 / fallback
/// - unreadable: 读不出元数据
#[derive(Serialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum SourceClass {
    Catalog,
    CatalogNoAlbum,
    NonCatalog,
    Unreadable,
}

const CATALOG_SIGNATURE: &str = "Provided to YouTube by";
const AUTO_GEN_SIGNATURE: &str = "Auto-generated by YouTube";

pub fn classify_source(meta: Option<&AudioMeta>) -> SourceClass {
    let Some(meta) = meta else {
        return SourceClass::Unreadable;
    };
    let syn = meta.synopsis.as_deref().unwrap_or("");
    let is_catalog = syn.contains(CATALOG_SIGNATURE) || syn.contains(AUTO_GEN_SIGNATURE);
    if is_catalog {
        if meta.album.as_deref().unwrap_or("").is_empty() {
            SourceClass::CatalogNoAlbum
        } else {
            SourceClass::Catalog
        }
    } else {
        SourceClass::NonCatalog
    }
}

/// 读一个音频文件的元数据。失败返回 None(调用方判 Unreadable)。
pub fn read_meta(path: &Path) -> Option<AudioMeta> {
    let tagged_file = lofty::read_from_path(path).ok()?;
    let duration = tagged_file.properties().duration().as_secs_f64();

    // primary_tag 提供统一访问(opus→VorbisComment, m4a→MP4 atom)
    let tag = tagged_file.primary_tag()?;
    let title = tag.get_string(&ItemKey::TrackTitle).map(String::from);
    let artist = tag.get_string(&ItemKey::TrackArtist).map(String::from);
    let album = tag.get_string(&ItemKey::AlbumTitle).map(String::from);
    let date = tag
        .get_string(&ItemKey::Year)
        .or_else(|| tag.get_string(&ItemKey::RecordingDate))
        .map(String::from);

    // synopsis / description / purl:YT Music 特有的 Vorbis Comment 键,
    // lofty 无标准 ItemKey 变体,以 ItemKey::Unknown(原始键名)形式存在,需遍历匹配。
    let mut synopsis = None;
    let mut description = None;
    let mut purl = None;
    for item in tag.items() {
        let key_str: Option<&str> = match item.key() {
            lofty::tag::ItemKey::Unknown(s) => Some(s.as_str()),
            _ => None,
        };
        let key_lower = key_str.map(|s| s.to_lowercase());
        let text = item.value().text().map(String::from);
        match key_lower.as_deref() {
            Some("synopsis") => synopsis = text,
            Some("description") => description = text,
            Some("purl") => purl = text,
            _ => {}
        }
    }

    let has_cover = !tag.pictures().is_empty();

    Some(AudioMeta {
        title,
        artist,
        album,
        date,
        synopsis,
        description,
        purl,
        duration: Some(duration),
        has_cover,
    })
}

/// 从 purl/description 提取 11 位 videoId。
pub fn find_video_id(meta: &AudioMeta) -> Option<String> {
    let hay = meta.purl.as_deref().or(meta.description.as_deref())?;
    let pos = hay.find("v=")?;
    let rest = &hay[pos + 2..];
    let id: String = rest.chars().take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '-').collect();
    if id.len() == 11 {
        Some(id)
    } else {
        None
    }
}

// ---- Tauri 命令 ----

#[derive(Serialize)]
pub struct MetaResult {
    pub meta: Option<AudioMeta>,
    pub source: SourceClass,
    pub video_id: Option<String>,
}

#[tauri::command]
pub fn read_audio_meta(path: String) -> MetaResult {
    let p = Path::new(&path);
    let meta = read_meta(p);
    let source = classify_source(meta.as_ref());
    let video_id = meta.as_ref().and_then(find_video_id);
    MetaResult { meta, source, video_id }
}

/// 扫描一个目录下所有音频,返回每条的元数据 + 来源分类。
/// 用于 R 页(校验)和 C 页(来源识别)批量扫描。
#[derive(Serialize)]
pub struct ScanItem {
    pub path: String,
    pub filename: String,
    pub meta: Option<AudioMeta>,
    pub source: SourceClass,
    pub video_id: Option<String>,
}

#[tauri::command]
pub fn scan_audio_dir(dir: String, recursive: Option<bool>) -> Vec<ScanItem> {
    let root = Path::new(&dir);
    if !root.is_dir() {
        return vec![];
    }
    let recursive = recursive.unwrap_or(true);
    let paths: Vec<std::path::PathBuf> = if recursive {
        walk(root)
    } else {
        std::fs::read_dir(root)
            .into_iter()
            .flatten()
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .collect()
    };

    let mut items = vec![];
    for path in paths {
        if !path.is_file() {
            continue;
        }
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("").to_lowercase();
        if !["opus", "m4a", "mp4", "mp3", "flac"].contains(&ext.as_str()) {
            continue;
        }
        let meta = read_meta(&path);
        let source = classify_source(meta.as_ref());
        let video_id = meta.as_ref().and_then(find_video_id);
        items.push(ScanItem {
            path: path.to_string_lossy().to_string(),
            filename: path.file_name().and_then(|n| n.to_str()).unwrap_or("").to_string(),
            meta,
            source,
            video_id,
        });
    }
    items
}

/// 手写递归遍历(避免引入 walkdir 依赖)
fn walk(root: &Path) -> Vec<std::path::PathBuf> {
    let mut out = vec![];
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in rd.flatten() {
            let p = entry.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.is_file() {
                out.push(p);
            }
        }
    }
    out
}
