#!/usr/bin/env python3
"""
Export Chrome/Chromium YouTube Music cookies to Netscape-format cookies.txt
for yt-dlp to use. Reliable alternative to yt-dlp's --cookies-from-browser
which breaks on Linux when GNOME Keyring has corrupt entries.

Usage:
    python src/export_cookies.py                     # default: cookies.txt
    python src/export_cookies.py --output /tmp/cookies.txt
"""
from __future__ import annotations

import argparse
import logging
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger("export_cookies")


def export_chrome_cookies(
    output_path: Path,
    domain: str = "youtube.com",
    browser: str = "chrome",
) -> int:
    """Export cookies from browser to Netscape-format file.

    Returns number of cookies exported.
    """
    try:
        import browser_cookie3
    except ImportError:
        log.error(
            "browser-cookie3 not installed. Run: pip install browser-cookie3"
        )
        return 0

    browser_map = {
        "chrome": browser_cookie3.chrome,
        "chromium": browser_cookie3.chromium,
        "brave": browser_cookie3.brave,
        "edge": browser_cookie3.edge,
        "firefox": browser_cookie3.firefox,
    }

    loader = browser_map.get(browser)
    if loader is None:
        log.error("Unsupported browser: %s (use: %s)", browser, ", ".join(browser_map))
        return 0

    try:
        cookies = list(loader(domain_name=domain))
    except Exception as e:
        log.warning("browser_cookie3.%s() failed: %s", browser, e)
        return 0

    if not cookies:
        log.warning("No cookies found for domain '%s' in %s", domain, browser)
        return 0

    # Write Netscape-format cookie jar
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by export_cookies.py\n")
        f.write("# https://curl.se/rfc/cookie_spec.html\n\n")

        for c in cookies:
            # domain, domain_flag, path, secure, http_only, expiry, name, value
            domain_flag = "TRUE" if c.domain.startswith(".") else "FALSE"
            secure = "TRUE" if c.secure else "FALSE"
            http_only = "TRUE" if hasattr(c, "http_only") and c.http_only else "FALSE"
            expiry = int(c.expires) if c.expires else 0
            f.write(
                f"{c.domain}\t{domain_flag}\t{c.path}\t"
                f"{secure}\t{expiry}\t{c.name}\t{c.value}\n"
            )

    log.info(
        "Exported %d cookies for '%s' from %s -> %s",
        len(cookies),
        domain,
        browser,
        output_path,
    )
    return len(cookies)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export cookies for yt-dlp")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("cookies.txt"),
        help="Output cookies.txt path (default: cookies.txt)",
    )
    parser.add_argument(
        "--domain",
        "-d",
        default="youtube.com",
        help="Cookie domain filter (default: youtube.com)",
    )
    parser.add_argument(
        "--browser",
        "-b",
        default="chrome",
        choices=["chrome", "chromium", "brave", "edge", "firefox"],
        help="Browser to extract cookies from (default: chrome)",
    )
    args = parser.parse_args()

    count = export_chrome_cookies(args.output, args.domain, args.browser)
    return 0 if count > 0 else 1


if __name__ == "__main__":
    import sys

    sys.exit(main())
