"""List downloaded songs that are NOT from YT Music's official catalog.

Discriminator: YT Music's official "Topic" channels embed a synopsis that
begins with "Provided to YouTube by {Label}" and ends with
"Auto-generated by YouTube." — these are licensed catalog releases.

Anything else (user-uploaded MVs, lyric videos, covers) lacks that signature.

Output: logs/non_ytmusic_report.md
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import config

CATALOG_SIGNATURE = "Provided to YouTube by"
AUTO_GEN_SIGNATURE = "Auto-generated by YouTube"


def _read_opus_meta(path: Path) -> dict | None:
    try:
        from mutagen.oggopus import OggOpus
        o = OggOpus(path)
        return {
            "title": (o.get("title") or [""])[0],
            "artist": (o.get("artist") or [""])[0],
            "album": (o.get("album") or [""])[0],
            "synopsis": (o.get("synopsis") or [""])[0],
            "description": (o.get("description") or [""])[0],
            "purl": (o.get("purl") or [""])[0],
            "date": (o.get("date") or [""])[0],
        }
    except Exception:
        return None


def _read_m4a_meta(path: Path) -> dict | None:
    try:
        from mutagen.mp4 import MP4
        f = MP4(path)
        t = f.tags or {}
        return {
            "title": (t.get("\xa9nam") or [""])[0],
            "artist": (t.get("\xa9ART") or [""])[0],
            "album": (t.get("\xa9alb") or [""])[0],
            "synopsis": (t.get("desc") or [""])[0],
            "description": (t.get("\xa9cmt") or [""])[0],
            "purl": "",
            "date": (t.get("\xa9day") or [""])[0],
        }
    except Exception:
        return None


def read_meta(path: Path) -> dict | None:
    ext = path.suffix.lower()
    if ext == ".opus":
        return _read_opus_meta(path)
    if ext in (".m4a", ".mp4"):
        return _read_m4a_meta(path)
    return None


def classify_source(meta: dict) -> str:
    """Return 'catalog' | 'no_album' | 'non_catalog'."""
    if not meta:
        return "unreadable"
    syn = meta.get("synopsis") or ""
    has_provided = CATALOG_SIGNATURE in syn
    has_auto_gen = AUTO_GEN_SIGNATURE in syn
    if has_provided or has_auto_gen:
        if not meta.get("album"):
            return "catalog_no_album"
        return "catalog"
    return "non_catalog"


def find_videoid(meta: dict) -> str:
    purl = meta.get("purl") or meta.get("description") or ""
    if "v=" in purl:
        return purl.split("v=", 1)[1].split("&")[0]
    return ""


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("-o", "--out",
                   default=str(config.LOGS_DIR / "non_ytmusic_report.md"),
                   help="Output markdown report path")
    p.add_argument("--include-no-album", action="store_true",
                   help="Also flag catalog entries that are missing album info")
    args = p.parse_args(argv)

    downloads_dir = config.DOWNLOADS_DIR
    audio_files = sorted([
        p for p in downloads_dir.rglob("*.opus")
    ] + [
        p for p in downloads_dir.rglob("*.m4a")
    ])

    rows: list[dict] = []
    for path in audio_files:
        meta = read_meta(path)
        cls = classify_source(meta) if meta else "unreadable"
        rows.append({
            "path": str(path.relative_to(downloads_dir.parent)),
            "subfolder": path.parent.name if path.parent != downloads_dir else "",
            "filename": path.name,
            "cls": cls,
            "meta": meta or {},
        })

    by_cls: dict[str, list[dict]] = {}
    for r in rows:
        by_cls.setdefault(r["cls"], []).append(r)

    non_catalog = by_cls.get("non_catalog", [])
    no_album = by_cls.get("catalog_no_album", [])
    catalog = by_cls.get("catalog", [])
    unreadable = by_cls.get("unreadable", [])

    out: list[str] = []
    out.append("# 非 YT Music 正版编录(fallback / 普通视频)报告")
    out.append("")
    out.append(f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    out.append(f"扫描目录: `{downloads_dir}`")
    out.append("")
    out.append("## 总览")
    out.append("")
    out.append(f"- 总文件数: **{len(rows)}**")
    out.append(f"- ✅ YT Music 正版编录(synopsis 带 *Provided to YouTube by ...*): **{len(catalog)}**")
    out.append(f"- 🟡 编录但缺 album(少见,可能元数据不全): **{len(no_album)}**")
    out.append(f"- ❌ 非编录(普通 YT 视频 / 用户上传 / fallback): **{len(non_catalog)}**")
    if unreadable:
        out.append(f"- ⚠️ 无法读取 metadata: **{len(unreadable)}**")
    out.append("")

    out.append("## 判定方法")
    out.append("")
    out.append("YT Music 正版编录的音频都来自自动生成的 *Topic* 频道,YouTube 会在 description 里写")
    out.append("`Provided to YouTube by {厂牌}` 起头、`Auto-generated by YouTube.` 收尾。")
    out.append("非编录的普通视频(用户上传 MV、Live、翻唱等)不会有这个签名。")
    out.append("")

    if non_catalog:
        out.append(f"## ❌ 非 YT Music 编录 (共 {len(non_catalog)} 条 — 优先 review)")
        out.append("")
        for r in non_catalog:
            m = r["meta"]
            vid = find_videoid(m)
            out.append(f"### `{r['filename']}`")
            out.append(f"- 路径: `downloads/{r['subfolder']}/{r['filename']}`")
            out.append(f"- 标题: `{m.get('title','')}`  艺人: `{m.get('artist','')}`")
            if m.get("album"):
                out.append(f"- 专辑: `{m.get('album','')}`")
            out.append(f"- videoId: `{vid}` · 发布日期: `{m.get('date','')}`")
            syn = (m.get("synopsis") or "")[:200]
            if syn:
                out.append(f"- synopsis 预览: `{syn!r}`")
            out.append("")
    else:
        out.append("## ✅ 没有非编录条目")
        out.append("")
        out.append("所有歌曲都来自 YT Music 正版编录(Topic 频道)。")
        out.append("")

    if args.include_no_album and no_album:
        out.append(f"## 🟡 编录但 album 字段为空 (共 {len(no_album)} 条)")
        out.append("")
        for r in no_album:
            m = r["meta"]
            out.append(f"- `{r['filename']}` 标题=`{m.get('title','')}` 艺人=`{m.get('artist','')}`")
        out.append("")

    if unreadable:
        out.append(f"## ⚠️ 无法读取 metadata (共 {len(unreadable)} 条)")
        out.append("")
        for r in unreadable:
            out.append(f"- `{r['path']}`")
        out.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out) + "\n", encoding="utf-8")

    print(f"Report: {out_path}")
    print(f"  catalog={len(catalog)}  catalog_no_album={len(no_album)}  "
          f"non_catalog={len(non_catalog)}  unreadable={len(unreadable)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
